# SPDX-License-Identifier: Apache-2.0
import torch

def mm(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor: ...
def embedding(t: torch.Tensor, f: torch.Tensor) -> torch.Tensor: ...
def unary(x: torch.Tensor, derivative: bool) -> torch.Tensor: ...
def timestep_grad(de: torch.Tensor, e: torch.Tensor, f: torch.Tensor) -> torch.Tensor: ...
