# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 RL-Kernel Contributors
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

import torch

from .core import atomic_save, bitdiff, _stitch

MODULES = ("attention", "ffn", "logp")
STAGES = (
    "input",
    "attention_norm",
    "q_projection",
    "k_projection",
    "v_projection",
    "q_norm",
    "k_norm",
    "query",
    "key",
    "value",
    "attention_core",
    "attention_output",
    "attention_residual",
    "mlp_norm",
    "mlp_gate",
    "mlp_up",
    "mlp_activation",
    "mlp_output",
    "output",
    "logits",
    "logp",
)
_LAYER_FILE = re.compile(
    r"^(?P<side>training|rollout)(?:-pid(?P<pid>\d+))?-rank(?P<rank>\d+)"
    r"-layer(?P<layer>\d+)-call(?P<call>\d+)$"
)


def _module(stage: str) -> str:
    if stage.startswith("mlp"):
        return "ffn"
    if stage in {"logits", "logp"}:
        return "logp"
    if stage == "output":
        return "residual"
    return "attention" if stage != "input" else "upstream"


def analyze_replay(directory: Path, paths: list[Path], *, output: Path | None = None):
    layers: dict[int, dict[str, list[Path]]] = {}
    errors = []
    for root in sorted({path.parent.parent for path in paths}):
        for path in sorted((root / "errors").glob("*.pt")):
            record = torch.load(path, map_location="cpu", weights_only=True)
            errors.append(f"capture failed ({path.name}): {record['error']}")
    first = None
    comparisons = []
    model_weights = []
    identities = set()
    sampling = set()
    expected_layers = set()
    sequence_lengths = set()
    for path in paths:
        # Filenames are generated by save_layer, and are not inferred framework ranks.
        match = _LAYER_FILE.match(path.stem)
        if match is None:
            errors.append(f"invalid diagnostic layer filename: {path}")
            continue
        side = match.group("side")
        layer = int(match.group("layer"))
        if side not in {"training", "rollout"}:
            errors.append(f"unknown diagnostic side: {path}")
            continue
        layers.setdefault(layer, {}).setdefault(side, []).append(path)
    for layer, pair in sorted(layers.items()):
        records = {}
        weights = {}
        layer_errors = []
        for side in ("training", "rollout"):
            records[side] = []
            for path in sorted(pair.get(side, [])):
                record = torch.load(path, map_location="cpu", weights_only=True)
                if record.get("schema_version") != "rlkernel.layer_replay.v1":
                    raise ValueError(f"invalid replay snapshot: {path}")
                # Training call 0 is the pre-update score; backward recomputation
                # and later actor forwards must not be silently mixed into it.
                if side == "training" and record["call"] != 0:
                    continue
                records[side].append(record)
                identities.add(record["frozen_tokens_sha256"])
                sampling.add(json.dumps(record["sampling"], sort_keys=True))
                expected_layers.add(record["metadata"].get("expected_layers"))
                sequence_lengths.add(record.get("sequence_length"))
            weights[side] = {}
            weight_paths: set[Path] = set()
            for path in pair.get(side, []):
                match = _LAYER_FILE.match(path.stem)
                if match is None:
                    continue
                # Require the exact worker's weights; another engine with the
                # same local rank cannot fill a missing evidence file.
                stem = path.stem.rsplit("-call", 1)[0]
                weight_paths.add(path.parent.parent / "weights" / f"{stem}.json")
            for path in sorted(weight_paths):
                if not path.exists():
                    layer_errors.append(f"missing runtime weight evidence: {path.name}")
                    continue
                for key, digest in json.loads(path.read_text(encoding="utf-8")).items():
                    if key in weights[side] and weights[side][key] != digest:
                        layer_errors.append(f"{side} weight replica differs: {key}")
                    weights[side][key] = digest
        if not all(records.values()):
            layer_errors.append("missing training or rollout layer snapshots")
        for side, captures in records.items():
            sizes = {r["metadata"].get("tp_size") for r in captures}
            ranks = {r["metadata"].get("tp_rank") for r in captures}
            if len(sizes) != 1 or None in sizes or ranks != set(range(next(iter(sizes)))):
                layer_errors.append(f"{side} tensor-parallel rank coverage is incomplete")
            if any("cp_size" in r["metadata"] for r in captures):
                cp_sizes = {r["metadata"].get("cp_size") for r in captures}
                pairs = {
                    (r["metadata"].get("tp_rank"), r["metadata"].get("cp_rank")) for r in captures
                }
                if (
                    len(sizes) != 1
                    or None in sizes
                    or len(cp_sizes) != 1
                    or None in cp_sizes
                    or pairs
                    != {
                        (t, c)
                        for t in range(next(iter(sizes)))
                        for c in range(next(iter(cp_sizes)))
                    }
                ):
                    layer_errors.append(f"{side} TP/CP rank coverage is incomplete")
        if not weights["training"] or not weights["rollout"]:
            layer_errors.append("missing runtime weight tiles")
        elif weights["training"] != weights["rollout"]:
            differences = [
                key
                for key in weights["training"].keys() | weights["rollout"].keys()
                if weights["training"].get(key) != weights["rollout"].get(key)
            ]
            layer_errors.append(f"runtime weights differ: {sorted(differences)[:3]}")
        model_weights.append(
            {
                side: hashlib.sha256(json.dumps(weights[side], sort_keys=True).encode()).hexdigest()
                for side in ("training", "rollout")
            }
        )
        selected = {int(p) for r in records["rollout"] for p in r["positions"].tolist() if p >= 0}
        if len(sequence_lengths) != 1 or None in sequence_lengths:
            layer_errors.append("missing or inconsistent frozen sequence length")
        elif selected != set(range(next(iter(sequence_lengths)) - 1)):
            layer_errors.append("rollout position coverage is incomplete for the frozen sequence")
        stages = []
        coverage = []
        contracts = {
            side: {json.dumps(r["metadata"].get("contract"), sort_keys=True) for r in captures}
            for side, captures in records.items()
        }
        contract_match = (
            all(contracts.values())
            and len(contracts["training"]) == 1
            and contracts["training"] == contracts["rollout"]
            and "null" not in contracts["training"]
        )
        if not contract_match:
            layer_errors.append(
                "observed Attention scale/norm/dropout contracts differ or are missing"
            )
        for stage in STAGES:
            left, left_errors = _stitch(records["training"], stage, selected)
            right, right_errors = _stitch(records["rollout"], stage, selected)
            layer_errors.extend(left_errors + right_errors)
            if not left or not right:
                coverage.append(stage)
                if stage in {"input", "output"}:
                    layer_errors.append(f"missing mandatory layer boundary: {stage}")
                continue
            if set(left) != selected or set(right) != selected:
                layer_errors.append(f"incomplete token coverage for {stage}")
            for position in sorted(set(left) & set(right)):
                delta = bitdiff(left[position], right[position])
                if not delta.get("comparable") or not delta.get("finite", False):
                    layer_errors.append(f"{stage}: invalid tensor comparison at token {position}")
                if not delta.get("comparable") or not delta.get("equal"):
                    row = {
                        "layer": layer,
                        "position": position,
                        "stage": stage,
                        "module": _module(stage),
                        **delta,
                    }
                    stages.append(row)
                    if first is None:
                        first = row
        comparisons.append(
            {
                "layer": layer,
                "identity_errors": layer_errors,
                "uncaptured_stages": coverage,
                "differences": stages,
                "compared_positions": len(selected),
                "contracts": {
                    side: [json.loads(v) for v in values] for side, values in contracts.items()
                },
            }
        )
        if first is not None and first["layer"] == layer:
            # These are declared observable dependencies, not proof of complete
            # cache/mask/internal arithmetic equivalence.
            dependencies = {
                "q_norm": ("q_projection",),
                "k_norm": ("k_projection",),
                "attention_core": ("query", "key", "value"),
                "mlp_activation": ("mlp_gate", "mlp_up"),
                "mlp_output": ("mlp_activation",),
            }.get(first["stage"], ())
            changed = {row["stage"] for row in stages}
            first["input_evidence"] = (
                "unknown"
                if not dependencies or any(d in coverage for d in dependencies)
                else "different"
                if any(d in changed for d in dependencies)
                else "equal"
            )
        if first is not None and first["layer"] == layer:
            position = first["position"]
            replay_tensors = {}
            for side in ("training", "rollout"):
                replay_tensors[side] = {}
                for stage in STAGES:
                    requested = (
                        {p for p in selected if p <= position}
                        if stage in {"key", "value"}
                        else {position}
                    )
                    values, _ = _stitch(records[side], stage, requested)
                    if values:
                        replay_tensors[side][stage] = {
                            "positions": torch.tensor(sorted(values)),
                            "values": torch.stack([values[p] for p in sorted(values)]),
                        }
            evidence = (output.parent if output else directory) / "first-divergence.pt"
            if output:
                evidence = output.with_suffix(".pt")
            atomic_save(
                evidence,
                {
                    "first_divergence": first,
                    "tensors": replay_tensors,
                    "source_snapshots": [str(p) for ps in pair.values() for p in ps],
                },
            )
        errors.extend(f"layer {layer}: {error}" for error in layer_errors)
    if len(identities) != 1 or len(sampling) != 1:
        errors.append("frozen token or sampling identity differs across captures")
    if (
        len(expected_layers) != 1
        or None in expected_layers
        or sorted(layers) != list(range(next(iter(expected_layers))))
    ):
        errors.append("decoder layer coverage does not match the actual model")
    identity_paths = {path.parent.parent / "identity" for path in paths}
    observed_identities = {side: [] for side in ("training", "rollout")}
    for root in identity_paths:
        for path in root.glob("*.json"):
            value = json.loads(path.read_text(encoding="utf-8"))
            side = value.pop("side")
            observed_identities[side].append(value)
    all_identities = observed_identities["training"] + observed_identities["rollout"]
    if (
        not all(observed_identities.values())
        or not all_identities
        or any(value != all_identities[0] for value in all_identities)
    ):
        errors.append("runtime token/mask/sampling identities are missing or different")
    elif {all_identities[0]["tokens"]} != identities:
        errors.append("captured layers do not belong to the verified frozen sample")
    endpoint = _endpoint(directory)
    errors.extend(validate_routes(directory))
    if endpoint.get("errors"):
        errors.extend(endpoint["errors"])
    head = analyze_head({path.parent.parent for path in paths})
    errors.extend(head["errors"])
    if first is None and head["first_divergence"]:
        first = {"layer": len(layers), "module": "lm_head", **head["first_divergence"]}
    if first is None and endpoint.get("bitwise_mismatch_count", 0):
        first = {
            "layer": len(layers),
            "stage": "logp",
            "module": "logp",
            "position": endpoint.get("first_divergence", {}).get("position"),
            "bitwise_mismatches": endpoint["bitwise_mismatch_count"],
        }
    status = "not_comparable" if errors else ("diverged" if first else "equal")
    report = {
        "schema_version": "rlkernel.diagnostic_report.v1",
        "status": status,
        "scope": "one frozen sample, pre-update eager forwards; captured stages only",
        "first_divergence": first,
        "errors": errors,
        "layers": comparisons,
        "endpoint": endpoint,
        "output_head": head,
        "runtime_identity": all_identities[0] if all_identities else None,
        "model_weights": model_weights,
        "next_checks": next_checks(first["module"]) if first else [],
    }
    return report


def analyze_head(roots: set[Path]) -> dict[str, Any]:
    records = {side: [] for side in ("training", "rollout")}
    weights = {side: {} for side in records}
    errors = []
    for root in roots:
        for path in (root / "heads").glob("*.pt"):
            record = torch.load(path, map_location="cpu", weights_only=True)
            side = record["side"]
            if side == "training" and record["call"] != 0:
                continue
            records[side].append(record)
        for side in records:
            head_paths = sorted(set((root / "weights").glob(f"{side}-*-head.json")))
            layer_paths = sorted(set((root / "weights").glob(f"{side}-*-layer0.json")))
            if not head_paths or {p.stem.removesuffix("-head") for p in head_paths} != {
                p.stem.removesuffix("-layer0") for p in layer_paths
            }:
                errors.append(f"{side} LM-head weight rank coverage is incomplete")
            for path in head_paths:
                for key, value in json.loads(path.read_text(encoding="utf-8")).items():
                    if key in weights[side] and weights[side][key] != value:
                        errors.append(f"{side} LM-head weight replica differs: {key}")
                    weights[side][key] = value
    if not weights["training"] or weights["training"] != weights["rollout"]:
        errors.append("LM-head runtime weights are missing or different")
    positions = {
        int(p)
        for record in records["rollout"]
        for p in record["metadata"]["stage_positions"]["logits"].tolist()
    }
    first = None
    for stage in ("head_input", "logits"):
        left, le = _stitch(records["training"], stage, positions)
        right, re = _stitch(records["rollout"], stage, positions)
        errors.extend(le + re)
        if not positions or set(left) != positions or set(right) != positions:
            errors.append(f"missing or incomplete {stage} evidence")
        for position in sorted(set(left) & set(right)):
            delta = bitdiff(left[position], right[position])
            if not delta.get("comparable") or not delta.get("finite", False):
                errors.append(f"invalid {stage} comparison at token {position}")
            if not delta.get("equal") and first is None:
                first = {"stage": stage, "position": position, **delta}
                for root in roots:
                    atomic_save(
                        root / "first-head-divergence.pt",
                        {
                            "first_divergence": first,
                            "training": left[position],
                            "rollout": right[position],
                        },
                    )
    return {
        "errors": errors,
        "first_divergence": first,
        "weight_fingerprints": {
            side: hashlib.sha256(json.dumps(value, sort_keys=True).encode()).hexdigest()
            for side, value in weights.items()
        },
    }


def validate_routes(directory: Path) -> list[str]:
    """Require executed module selections, not just requested command flags."""
    from rl_engine.integrations.runtime import (
        _contains_fallback,
        _runtime_platform,
    )
    from examples.vime_rocm_attention_ablation.validate_artifacts import _values_for_keys

    manifests = list(directory.glob("manifest.json")) + list(directory.glob("arms/*/launch.json"))
    if len(manifests) != 1:
        return ["missing or ambiguous launch manifest for operator attribution"]
    value = json.loads(manifests[0].read_text(encoding="utf-8"))
    env = value.get("runtime_env", {}).get("env_vars", value.get("environment", {}))
    expected = {name: env.get(f"RL_KERNEL_{name.upper()}_CASE") for name in MODULES}
    files = list(directory.glob("**/readbacks/*.json"))
    readbacks = [json.loads(path.read_text(encoding="utf-8")) for path in files]
    errors = []
    for framework in ("megatron", "vllm"):
        records = [v for v in readbacks if v.get("framework") == framework]
        if not records:
            errors.append(f"missing {framework} runtime operator readbacks")
        for name, case in expected.items():
            if case not in {"P/P", "R/R"}:
                errors.append(f"missing requested {name} diagnostic case")
                continue
            calls = 0
            for record in records:
                actual = record.get("plan", {}).get("cases", {}).get(name, {}).get("case_id")
                if actual != case:
                    errors.append(f"{framework}/{name} actual case {actual} differs from {case}")
                if record.get("fallbacks"):
                    errors.append(f"{framework} recorded an operator fallback")
                operator = record.get("operators", {}).get(name, {})
                calls += int(operator.get("call_count", 0))
                if not operator:
                    continue  # Installed-only processes are not execution evidence.
                label = f"{framework}/{name}"
                implementation = "rl_kernel" if case == "R/R" else "production"
                if (
                    operator.get("case_id") != case
                    or operator.get("implementation") != implementation
                ):
                    errors.append(f"{label} executed a different module selection")
                if int(operator.get("call_count", 0)) <= 0:
                    errors.append(f"{label} recorded zero calls")
                if operator.get("execution_mode") != "eager":
                    errors.append(f"{label} did not execute the declared eager diagnostic route")
                provenance = operator.get("provenance", {})
                if _contains_fallback(provenance):
                    errors.append(f"{label} executed a fallback")
                backend = str(operator.get("backend_id", ""))
                if case == "P/P":
                    if backend != f"{framework}.production.{name}":
                        errors.append(f"{label} did not prove the production backend")
                elif not backend.startswith(("rlkernel.", "pytorch-vocab-parallel-logp")):
                    errors.append(f"{label} did not prove an RL Kernel backend")
                elif _runtime_platform(provenance) not in {"cuda", "rocm"} or not any(
                    isinstance(value, str) and value.strip()
                    for value in _values_for_keys(provenance, {"actual_backend"})
                ):
                    errors.append(f"{label} is missing executed backend/platform provenance")
                elif _runtime_platform(provenance) == "rocm":
                    from examples.vime_rocm_attention_ablation.validate_artifacts import (
                        _validate_rlkernel_record,
                        _validate_strict_dense_record,
                    )

                    if name == "attention":
                        _validate_rlkernel_record(
                            operator, label=label, framework=framework, errors=errors
                        )
                    else:
                        _validate_strict_dense_record(
                            operator,
                            module=name,
                            framework=framework,
                            label=label,
                            errors=errors,
                            diagnostic=True,
                        )
            if calls == 0 and not (framework == "megatron" and name == "logp" and case == "P/P"):
                errors.append(f"{framework}/{name} has no executed operator evidence")
    return errors


def _endpoint(directory: Path) -> dict[str, Any]:
    from examples.vime_rocm_attention_ablation.validate_artifacts import (
        _sidecar_samples,
        compare_train_rollout_logps,
        slice_response_mask_for_cp,
    )

    roots = list(directory.rglob("mismatch_sidecars")) + list(directory.rglob("mismatch-sidecars"))
    if len(roots) != 1:
        return {"errors": ["missing or ambiguous final logprob sidecars"]}
    files = sorted(roots[0].glob("*.pt"))
    if not files:
        return {"errors": ["no final logprob sidecars"]}
    payload = torch.load(files[0], map_location="cpu", weights_only=True)
    tp, cp = int(payload["tensor_parallel_size"]), int(payload["context_parallel_size"])
    report = compare_train_rollout_logps(
        roots[0],
        require_exact=False,
        tensor_parallel_size=tp,
        context_parallel_size=cp,
    )
    first = None
    for path in files:
        for sample in _sidecar_samples(path, tensor_parallel_size=tp, context_parallel_size=cp):
            mask = sample["mask"]
            left, right = sample["training"][mask], sample["rollout"][mask]
            # The validator above checks full CP coverage and a globally
            # nonempty response. Short responses may leave a local rank empty.
            if left.numel() == right.numel() == 0:
                continue
            delta = bitdiff(left, right)
            if not delta.get("comparable") or not delta.get("finite", False):
                report.setdefault("errors", []).append(f"invalid final logprob evidence: {path}")
            if not delta.get("first_index"):
                continue
            length, response = sample["total_length"], sample["response_length"]
            positions = slice_response_mask_for_cp(
                torch.arange(length - response - 1, length - 1),
                total_length=length,
                response_length=response,
                context_parallel_size=cp,
                context_parallel_rank=sample["key"][-1],
            )
            position = int(positions[mask][delta["first_index"][0]])
            if first is None or position < first["position"]:
                first = {"position": position, "sidecar": str(path), **delta}
                atomic_save(
                    directory / "first-logp-divergence.pt",
                    {
                        "first_divergence": first,
                        "positions": positions,
                        "training": sample["training"],
                        "rollout": sample["rollout"],
                        "mask": mask,
                    },
                )
    if first is not None:
        report["first_divergence"] = first
    # Keep the validator's logical count: TP replicas repeat the same logprobs.
    return report


def next_checks(module: str) -> list[str]:
    return {
        "upstream": [
            "The decoder input already differs: inspect embeddings and "
            "weight loading before blaming this layer."
        ],
        "attention": [
            "Compare Q/K/V before the Attention core; inspect RoPE, "
            "positions, causal boundaries and KV content.",
            "With identical inputs, replay one change at a time: "
            "accumulation dtype, cast points, split/merge order.",
        ],
        "ffn": [
            "Compare gate/up projection, activation and down projection boundaries.",
            "With identical weights/inputs, inspect SwiGLU rounding, GEMM "
            "reduction and TP communication.",
        ],
        "logp": [
            "Compare selected token and vocabulary ownership, then "
            "temperature/top-p support and LSE reduction."
        ],
        "lm_head": ["Compare final norm and vocabulary projection inputs/weights before scoring."],
        "residual": ["Compare the final FFN output, bias, dropout and residual addition."],
    }.get(
        module,
        ["Inspect the preceding captured stage before attributing this boundary to a kernel."],
    )
