# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 RL-Kernel Contributors

"""Testing helpers for RL-shaped kernel validation."""

from .attention_comparison import (
    AttentionComparisonInputs,
    AttentionComparisonReport,
    AttentionPathDrift,
    AttentionPathResult,
    DecodeAttentionInputs,
    DecodeKVCacheMetadata,
    DriftStats,
    TransformerEngineUnavailable,
    compare_decode_kv_replay,
    compare_single_gpu_attention,
    compare_single_gpu_rope_attention,
    decode_kv_cache_fingerprint,
    decode_prefix_cache_fingerprint,
    decode_rope_identity_fingerprint,
    run_chunked_query_attention,
    run_decode_full_prefill_reference,
    run_decode_kv_replay,
    run_decode_strict_shared_core,
    run_full_attention,
    run_fused_like_rope_attention,
    run_paged_kv_attention,
    run_strict_shared_core_attention,
    run_strict_shared_core_chunked_attention,
    run_strict_shared_core_paged_layout_attention,
    run_unfused_rope_attention,
    transformer_engine_context_parallel_available,
)
from .gemma4_workload import Gemma4Manifest, Gemma4WorkloadError
from .gemma4_workload import load_manifest as load_gemma4_manifest
from .gemma4_workload import reference_payload as gemma4_reference_payload
from .reference_ops import (
    active_token_count,
    compute_policy_ratio,
    compute_reference_kl,
    masked_mean,
    masked_sum,
    selected_logprobs_reference,
    summarize_kernel_drift,
)
from .rl_batch import SyntheticRLKernelBatch, make_synthetic_rl_kernel_batch
from .ws1_workload import (
    LogicalBatch,
    PhysicalLayout,
    WorkloadError,
    WS1Manifest,
    apply_chunking,
    apply_packing,
    apply_padding,
    build_logical_batch,
    fixture_hash,
    load_manifest,
    reference_payload,
    restore_logical_order,
    restore_logical_order_from_padded,
)

__all__ = [
    "AttentionComparisonInputs",
    "AttentionComparisonReport",
    "AttentionPathDrift",
    "AttentionPathResult",
    "DecodeAttentionInputs",
    "DecodeKVCacheMetadata",
    "DriftStats",
    "Gemma4Manifest",
    "Gemma4WorkloadError",
    "SyntheticRLKernelBatch",
    "TransformerEngineUnavailable",
    "active_token_count",
    "compare_single_gpu_rope_attention",
    "compare_single_gpu_attention",
    "compare_decode_kv_replay",
    "decode_kv_cache_fingerprint",
    "decode_rope_identity_fingerprint",
    "decode_prefix_cache_fingerprint",
    "LogicalBatch",
    "PhysicalLayout",
    "SyntheticRLKernelBatch",
    "WS1Manifest",
    "WorkloadError",
    "active_token_count",
    "apply_chunking",
    "apply_padding",
    "apply_packing",
    "build_logical_batch",
    "compute_policy_ratio",
    "compute_reference_kl",
    "fixture_hash",
    "gemma4_reference_payload",
    "load_gemma4_manifest",
    "load_manifest",
    "make_synthetic_rl_kernel_batch",
    "masked_mean",
    "masked_sum",
    "run_chunked_query_attention",
    "run_decode_full_prefill_reference",
    "run_decode_kv_replay",
    "run_decode_strict_shared_core",
    "run_fused_like_rope_attention",
    "run_full_attention",
    "run_paged_kv_attention",
    "run_unfused_rope_attention",
    "run_strict_shared_core_attention",
    "run_strict_shared_core_chunked_attention",
    "run_strict_shared_core_paged_layout_attention",
    "reference_payload",
    "restore_logical_order",
    "restore_logical_order_from_padded",
    "selected_logprobs_reference",
    "summarize_kernel_drift",
    "transformer_engine_context_parallel_available",
]
